In [12]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [13]:
import os
os.listdir('/content/drive/MyDrive')

['Classroom',
 'Untitled document.gdoc',
 '20240131.kine',
 'km_20240131_720p_30f_20240131_081517 (1).mp4',
 'km_20240131_720p_30f_20240131_081517.mp4',
 '1RV23IM022 (1).jpg',
 'DOC-20240313-WA0005 (1)._copy.pdf',
 'DOC-20240313-WA0005._copy.pdf',
 'HELLIX_136.docx',
 'el updated.pptx',
 'C EL REPORT[1].pdf',
 '5. EL Poster[1].pdf',
 'Kaushik Gupta1RV23IM022.pptx',
 '2. BASKET COURSE III SEM 30 Sept 2024.pdf',
 '20613696-hd_1920_1080_30fps.mp4',
 'Jay Report 2.pdf_20241214_113744_0000.png.PNG',
 'IMG_1896.png',
 '1.docx',
 'IMG_6192.png',
 'IMG_6215.jpeg',
 'ad34bed1-9a45-4c19-b487-e94b254dedb0.jpeg',
 '1RV23IM022.jpg',
 'IMG_6670.jpeg',
 'Data Science for Engineers.pdf',
 'Resume_KG.jpg',
 'Corporate Social Responsibility.pdf',
 'TEAM_10_PAPER.pdf.pdf',
 'VI semester institutional elective 12-02-2026.xlsx',
 'Colab Notebooks',
 'Kaushik_Gupta_1RV23IM022_-5 (6).pdf',
 'Kaushik_Gupta_1RV23IM022_-5 (5).pdf',
 'Kaushik_Gupta_1RV23IM022_-5 (4).pdf',
 'Kaushik_Gupta_1RV23IM022_-5 (3).pdf',
 'Kaushik_Gupta_1RV23IM022_-5 (2).pdf',
 'Kaushik_Gupta_1RV23IM022_-5 (1).pdf',
 'Kaushik_Gupta_1RV23IM022_-5.pdf',
 'IMG_4851 (1).jpeg',
 'IMG_4851.jpeg',
 'Exercise 3.xlsx',
 'procurement_analytics',
 'Distribution_Network_Optimization']

In [14]:
import os
project_path = "/content/drive/MyDrive/Distribution_Network_Optimization/Data/Raw"
print(os.listdir(project_path))

['Supply chain logistics problem.xlsx']

In [15]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [16]:
import os
base = "/content/drive/MyDrive/Distribution_Network_Optimization"
print(os.listdir(f"{base}/Data/Raw"))

['Supply chain logistics problem.xlsx']

In [17]:
import pandas as pd
file_path = "/content/drive/MyDrive/Distribution_Network_Optimization/Data/Raw/Supply chain logistics problem.xlsx"
xls = pd.ExcelFile(file_path)
print(xls.sheet_names)

['OrderList', 'FreightRates', 'WhCosts', 'WhCapacities', 'ProductsPerPlant', 'VmiCustomers', 'PlantPorts']

In [18]:
import pandas as pd

sheets = [
    "OrderList",
    "FreightRates",
    "WhCosts",
    "WhCapacities",
    "ProductsPerPlant",
    "VmiCustomers",
    "PlantPorts"
]

tables = {}

for sheet in sheets:
    tables[sheet] = pd.read_excel(file_path, sheet_name=sheet)
    print(f"{sheet:20} shape: {tables[sheet].shape}")

OrderList            shape: (9215, 14)
FreightRates         shape: (1540, 11)
WhCosts              shape: (19, 2)
WhCapacities         shape: (19, 2)
ProductsPerPlant     shape: (2036, 2)
VmiCustomers         shape: (14, 2)
PlantPorts           shape: (22, 2)

In [19]:
tables["OrderList"].head()

,Order ID,Order Date,Origin Port,Carrier,TPT,Service Level,Ship ahead day count,Ship Late Day count,Customer,Product ID,Plant Code,Destination Port,Unit quantity,Weight
0,1.447296e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,808,14.30
1,1.447158e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,3188,87.94
2,1.447139e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2331,61.20
3,1.447364e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,847,16.16
4,1.447364e+09,2013-05-26,PORT09,V44_3,1,CRF,3,0,V55555_53,1700106,PLANT16,PORT09,2163,52.34

In [20]:
tables["OrderList"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9215 entries, 0 to 9214
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Order ID              9215 non-null   float64
 1   Order Date            9215 non-null   datetime64[ns]
 2   Origin Port           9215 non-null   object
 3   Carrier               9215 non-null   object
 4   TPT                   9215 non-null   int64
 5   Service Level         9215 non-null   object
 6   Ship ahead day count  9215 non-null   int64
 7   Ship Late Day count   9215 non-null   int64
 8   Customer              9215 non-null   object
 9   Product ID            9215 non-null   int64
 10  Plant Code            9215 non-null   object
 11  Destination Port      9215 non-null   object
 12  Unit quantity         9215 non-null   int64
 13  Weight                9215 non-null   float64
dtypes: datetime64[ns](1), float64(2), int64(5), object(6)
memory usage: 1008.0+ KB

In [21]:
print("Unique Customers :", tables["OrderList"]["Customer"].nunique())
print("Unique Plants    :", tables["OrderList"]["Plant Code"].nunique())
print("Unique Products  :", tables["OrderList"]["Product ID"].nunique())

Unique Customers : 46
Unique Plants    : 7
Unique Products  : 772

In [22]:
tables["WhCosts"]

         WH  Cost/unit
0   PLANT15   1.415063
1   PLANT17   0.428947
2   PLANT18   2.036254
3   PLANT05   0.488144
4   PLANT02   0.477504
5   PLANT01   0.566976
6   PLANT06   0.554088
7   PLANT10   0.493582
8   PLANT07   0.371424
9   PLANT14   0.634330
10  PLANT16   1.919808
11  PLANT12   0.773132
12  PLANT11   0.555247
13  PLANT09   0.465071
14  PLANT03   0.517502
15  PLANT13   0.469707
16  PLANT19   0.639763
17  PLANT08   0.522857
18  PLANT04   0.428503

In [23]:
tables["WhCosts"].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   WH         19 non-null     object
 1   Cost/unit  19 non-null     float64
dtypes: float64(1), object(1)
memory usage: 436.0+ bytes

In [24]:
tables["WhCapacities"]

   Plant ID  Daily Capacity
0   PLANT15               11
1   PLANT17                8
2   PLANT18              111
3   PLANT05              385
4   PLANT02              138
5   PLANT01             1070
6   PLANT06               49
7   PLANT10              118
8   PLANT07              265
9   PLANT14              549
10  PLANT16              457
11  PLANT12              209
12  PLANT11              332
13  PLANT09               11
14  PLANT03             1013
15  PLANT13              490
16  PLANT19                7
17  PLANT08               14
18  PLANT04              554

In [25]:
tables["PlantPorts"]

   Plant Code    Port
0     PLANT01  PORT01
1     PLANT01  PORT02
2     PLANT02  PORT03
3     PLANT03  PORT04
4     PLANT04  PORT05
5     PLANT05  PORT06
6     PLANT06  PORT06
7     PLANT07  PORT01
8     PLANT07  PORT02
9     PLANT08  PORT04
10    PLANT09  PORT04
11    PLANT10  PORT01
12    PLANT10  PORT02
13    PLANT11  PORT04
14    PLANT12  PORT04
15    PLANT13  PORT04
16    PLANT14  PORT07
17    PLANT15  PORT08
18    PLANT16  PORT09
19    PLANT17  PORT10
20    PLANT18  PORT11
21    PLANT19  PORT04

In [26]:
tables["FreightRates"].head()

,Carrier,orig_port_cd,dest_port_cd,minm_wgh_qty,max_wgh_qty,svc_cd,minimum cost,rate,mode_dsc,tpt_day_cnt,Carrier type
0,V444_6,PORT08,PORT09,250.0,499.99,DTD,43.2272,0.7132,AIR,2,V88888888_0
1,V444_6,PORT08,PORT09,65.0,69.99,DTD,43.2272,0.7512,AIR,2,V88888888_0
2,V444_6,PORT08,PORT09,60.0,64.99,DTD,43.2272,0.7892,AIR,2,V88888888_0
3,V444_6,PORT08,PORT09,50.0,54.99,DTD,43.2272,0.8272,AIR,2,V88888888_0
4,V444_6,PORT08,PORT09,35.0,39.99,DTD,43.2272,1.0552,AIR,2,V88888888_0

In [27]:
tables["ProductsPerPlant"].head()

  Plant Code  Product ID
0    PLANT15     1698815
1    PLANT17     1664419
2    PLANT17     1664426
3    PLANT17     1672826
4    PLANT17     1674916

In [28]:
tables["VmiCustomers"]

   Plant Code                Customers
0     PLANT02        V5555555555555_16
1     PLANT02      V555555555555555_29
2     PLANT02             V555555555_3
3     PLANT02        V55555555555555_8
4     PLANT02              V55555555_9
5     PLANT02                V55555_10
6     PLANT02              V55555555_5
7     PLANT06      V555555555555555_18
8     PLANT06                V55555_10
9     PLANT10      V555555555555555_29
10    PLANT10               V555555_34
11    PLANT10  V5555555555555555555_54
12    PLANT10                V55555_10
13    PLANT11  V5555555555555555555_54

In [29]:
orders = tables["OrderList"]
whc = tables["WhCosts"]
whcap = tables["WhCapacities"]

In [30]:
active_plants = set(orders["Plant Code"].unique())
print(active_plants)
print(f"Number of active plants: {len(active_plants)}")

{'PLANT09', 'PLANT03', 'PLANT13', 'PLANT16', 'PLANT04', 'PLANT08', 'PLANT12'}
Number of active plants: 7

In [31]:
selected_new = {"PLANT01", "PLANT07", "PLANT14"}
candidate_plants = active_plants | selected_new
print(sorted(candidate_plants))
print(f"Total candidate plants: {len(candidate_plants)}")

['PLANT01', 'PLANT03', 'PLANT04', 'PLANT07', 'PLANT08', 'PLANT09', 'PLANT12', 'PLANT13', 'PLANT14', 'PLANT16']
Total candidate plants: 10

In [32]:
active_plants = set(orders['Plant Code'].unique())
selected_new = {'PLANT01', 'PLANT07', 'PLANT14'}
candidate_plants = active_plants | selected_new

merged = whc.merge(whcap, left_on='WH', right_on='Plant ID')
print(f"merged (all 19): {merged.shape}")

warehouse_master = merged[merged['WH'].isin(candidate_plants)].copy()
print(f"warehouse_master: {warehouse_master.shape}")

warehouse_master

merged (all 19): (19, 4)
warehouse_master: (10, 4)

         WH  Cost/unit Plant ID  Daily Capacity
5   PLANT01   0.566976  PLANT01             1070
8   PLANT07   0.371424  PLANT07              265
9   PLANT14   0.634330  PLANT14              549
10  PLANT16   1.919808  PLANT16              457
11  PLANT12   0.773132  PLANT12              209
13  PLANT09   0.465071  PLANT09               11
14  PLANT03   0.517502  PLANT03             1013
15  PLANT13   0.469707  PLANT13              490
17  PLANT08   0.522857  PLANT08               14
18  PLANT04   0.428503  PLANT04              554

In [33]:
mismatch = (warehouse_master['WH'] != warehouse_master['Plant ID']).sum()
print(f"Rows where WH != Plant ID: {mismatch}")

Rows where WH != Plant ID: 0

In [34]:
warehouse_master.columns

Index(['WH', 'Cost/unit', 'Plant ID', 'Daily Capacity '], dtype='object')

In [35]:
warehouse_master = warehouse_master.drop(columns=['Plant ID'])
warehouse_master = warehouse_master.rename(columns={
    'WH': 'plant_code',
    'Cost/unit': 'variable_cost_per_unit',
    'Daily Capacity ': 'daily_capacity_orders'
})

In [36]:
warehouse_master.columns

Index(['plant_code', 'variable_cost_per_unit', 'daily_capacity_orders'], dtype='object')

In [37]:
warehouse_master['is_currently_active'] = warehouse_master['plant_code'].isin(active_plants)
warehouse_master = warehouse_master.sort_values(
    'is_currently_active',
    ascending=False
).reset_index(drop=True)
print(f"Active: {warehouse_master['is_currently_active'].sum()}")
print(f"New candidates: {(~warehouse_master['is_currently_active']).sum()}")
warehouse_master

Active: 7
New candidates: 3

,plant_code,variable_cost_per_unit,daily_capacity_orders,is_currently_active
0,PLANT16,1.919808,457,True
1,PLANT12,0.773132,209,True
2,PLANT09,0.465071,11,True
3,PLANT03,0.517502,1013,True
4,PLANT13,0.469707,490,True
5,PLANT08,0.522857,14,True
6,PLANT04,0.428503,554,True
7,PLANT01,0.566976,1070,False
8,PLANT07,0.371424,265,False
9,PLANT14,0.634330,549,False

In [38]:
MIN_ORDERS_FOR_OWN_AVERAGE = 30
network_avg = orders['Unit quantity'].sum() / len(orders)

per_plant = orders.groupby('Plant Code').agg(
    order_count=('Order ID', 'count'),
    total_units=('Unit quantity', 'sum')
).reset_index()

per_plant['own_avg_order_size'] = (
    per_plant['total_units'] / per_plant['order_count']
)

print(f"Plants present in order history: {len(per_plant)}")
print(f"Missing from lookup entirely: {candidate_plants - set(per_plant['Plant Code'])}")

conversion_lookup = (
    per_plant.set_index('Plant Code')
             .reindex(sorted(candidate_plants))
             .reset_index()
)

conversion_lookup['order_count'] = (
    conversion_lookup['order_count'].fillna(0).astype(int)
)

conversion_lookup['reliable_sample'] = (
    conversion_lookup['order_count'] >= MIN_ORDERS_FOR_OWN_AVERAGE
)

conversion_lookup['conversion_factor'] = (
    conversion_lookup['own_avg_order_size']
    .where(conversion_lookup['reliable_sample'], network_avg)
)

conversion_lookup['factor_source'] = (
    conversion_lookup['reliable_sample']
    .map({True: 'own history', False: 'network fallback'})
)

conversion_lookup[['Plant Code', 'order_count', 'own_avg_order_size',
                   'conversion_factor', 'factor_source']]

Plants present in order history: 7
Missing from lookup entirely: {'PLANT01', 'PLANT14', 'PLANT07'}

,Plant Code,order_count,own_avg_order_size,conversion_factor,factor_source
0,PLANT01,0,NaN,3202.747151,network fallback
1,PLANT03,8541,3349.914179,3349.914179,own history
2,PLANT04,1,348.000000,3202.747151,network fallback
3,PLANT07,0,NaN,3202.747151,network fallback
4,PLANT08,102,2715.764706,2715.764706,own history
5,PLANT09,12,18652.500000,3202.747151,network fallback
6,PLANT12,300,373.333333,373.333333,own history
7,PLANT13,86,504.406977,504.406977,own history
8,PLANT14,0,NaN,3202.747151,network fallback
9,PLANT16,173,1416.953757,1416.953757,own history

In [39]:
conversion_lookup = conversion_lookup.rename(columns={
    "Plant Code": "plant_code"
})

conversion_lookup.columns

Index(['plant_code', 'order_count', 'total_units', 'own_avg_order_size',
       'reliable_sample', 'conversion_factor', 'factor_source'],
      dtype='object')

In [40]:
before_rows = len(warehouse_master)

warehouse_master = warehouse_master.merge(
    conversion_lookup[['plant_code', 'order_count', 'conversion_factor', 'factor_source']],
    on='plant_code',
    how='left'
)

assert len(warehouse_master) == before_rows, "Merge changed row count -- investigate before proceeding"
assert warehouse_master['conversion_factor'].isnull().sum() == 0, "Unmatched plant found -- investigate"

warehouse_master['daily_capacity_units'] = (
    warehouse_master['daily_capacity_orders'] * warehouse_master['conversion_factor']
).round(0)

warehouse_master = warehouse_master.sort_values(
    'is_currently_active',
    ascending=False
).reset_index(drop=True)

print(f"Total daily capacity (units): {warehouse_master['daily_capacity_units'].sum():,.0f}")

warehouse_master

Total daily capacity (units): 12,247,745

,plant_code,variable_cost_per_unit,daily_capacity_orders,is_currently_active,order_count,conversion_factor,factor_source,daily_capacity_units
0,PLANT16,1.919808,457,True,173,1416.953757,own history,647548.0
1,PLANT12,0.773132,209,True,300,373.333333,own history,78027.0
2,PLANT09,0.465071,11,True,12,3202.747151,network fallback,35230.0
3,PLANT03,0.517502,1013,True,8541,3349.914179,own history,3393463.0
4,PLANT13,0.469707,490,True,86,504.406977,own history,247159.0
5,PLANT08,0.522857,14,True,102,2715.764706,own history,38021.0
6,PLANT04,0.428503,554,True,1,3202.747151,network fallback,1774322.0
7,PLANT01,0.566976,1070,False,0,3202.747151,network fallback,3426939.0
8,PLANT07,0.371424,265,False,0,3202.747151,network fallback,848728.0
9,PLANT14,0.634330,549,False,0,3202.747151,network fallback,1758308.0

In [41]:
print("Nulls check:")
print(orders[['Customer','Unit quantity','Weight','Order ID']].isnull().sum())

customer_demand = orders.groupby('Customer').agg(
    total_units_period=('Unit quantity', 'sum'),
    total_weight_period=('Weight', 'sum'),
    order_count=('Order ID', 'count')
).reset_index()

print(f"Distinct customers: {customer_demand.shape[0]}")
print(f"Units match: {customer_demand['total_units_period'].sum() == orders['Unit quantity'].sum()}")
print(f"Order count match: {customer_demand['order_count'].sum() == len(orders)}")

customer_demand = customer_demand.sort_values(
    'total_units_period',
    ascending=False
).reset_index(drop=True)

customer_demand.head()

Nulls check:
Customer         0
Unit quantity    0
Weight           0
Order ID         0
dtype: int64
Distinct customers: 46
Units match: True
Order count match: True

          Customer  total_units_period  total_weight_period  order_count
0      V55555555_5             8020417         21970.357577          531
1  V55555555555_28             5293676          3451.853820          203
2     V55555555_32             1914858          4449.030135          241
3        V55555_26             1909058         16567.123311          340
4         V55555_2             1512452         18717.648999          758

In [42]:
PLANNING_HORIZON_DAYS = 5

customer_demand['avg_daily_demand_units'] = (
    customer_demand['total_units_period'] / PLANNING_HORIZON_DAYS
).round(1)

customer_demand = customer_demand.sort_values(
    'total_units_period',
    ascending=False
).reset_index(drop=True)

largest_customer_demand = customer_demand['avg_daily_demand_units'].max()
largest_dc_capacity = warehouse_master['daily_capacity_units'].max()

print(f"Largest customer demand: {largest_customer_demand:,.0f} | Largest DC capacity: {largest_dc_capacity:,.0f}")
print(f"A single DC could serve the top customer alone: {largest_customer_demand <= largest_dc_capacity}")

total_capacity = warehouse_master['daily_capacity_units'].sum()
total_demand = customer_demand['avg_daily_demand_units'].sum()

print(f"Utilization: {total_demand/total_capacity:.1%}")

customer_demand.head()

Largest customer demand: 1,604,083 | Largest DC capacity: 3,426,939
A single DC could serve the top customer alone: True
Utilization: 48.2%

,Customer,total_units_period,total_weight_period,order_count,avg_daily_demand_units
0,V55555555_5,8020417,21970.357577,531,1604083.4
1,V55555555555_28,5293676,3451.853820,203,1058735.2
2,V55555555_32,1914858,4449.030135,241,382971.6
3,V55555_26,1909058,16567.123311,340,381811.6
4,V55555_2,1512452,18717.648999,758,302490.4

In [43]:
warehouse_master.to_csv(
    f"{base}/Data/Processed/warehouse_master.csv",
    index=False
)

customer_demand.to_csv(
    f"{base}/Data/Processed/customer_demand.csv",
    index=False
)

print("Processed tables saved successfully.")

Processed tables saved successfully.

In [44]:
import numpy as np
np.random.seed(42)

hub_cities = {
    'Mumbai': (19.0760,72.8777),
    'Delhi NCR': (28.7041,77.1025),
    'Bengaluru': (12.9716,77.5946),
    'Chennai': (13.0827,80.2707),
    'Kolkata': (22.5726,88.3639),
    'Pune': (18.5204,73.8567),
    'Ahmedabad': (23.0225,72.5714),
    'Hyderabad': (17.3850,78.4867),
    'Nagpur': (21.1458,79.0882),
    'Indore': (22.7196,75.8577),
}

assert len(hub_cities) >= len(warehouse_master), "Not enough distinct cities for the DC count"

hub_names = list(hub_cities.keys())
assigned = np.random.choice(hub_names, size=len(warehouse_master), replace=False)

warehouse_master['city'] = assigned
warehouse_master['latitude'] = warehouse_master['city'].map(lambda c: hub_cities[c][0])
warehouse_master['longitude'] = warehouse_master['city'].map(lambda c: hub_cities[c][1])

print(f"Duplicate city assignments: {warehouse_master['city'].duplicated().sum()}")

warehouse_master

Duplicate city assignments: 0

,plant_code,variable_cost_per_unit,daily_capacity_orders,is_currently_active,order_count,conversion_factor,factor_source,daily_capacity_units,city,latitude,longitude
0,PLANT16,1.919808,457,True,173,1416.953757,own history,647548.0,Nagpur,21.1458,79.0882
1,PLANT12,0.773132,209,True,300,373.333333,own history,78027.0,Delhi NCR,28.7041,77.1025
2,PLANT09,0.465071,11,True,12,3202.747151,network fallback,35230.0,Pune,18.5204,73.8567
3,PLANT03,0.517502,1013,True,8541,3349.914179,own history,3393463.0,Mumbai,19.0760,72.8777
4,PLANT13,0.469707,490,True,86,504.406977,own history,247159.0,Hyderabad,17.3850,78.4867
5,PLANT08,0.522857,14,True,102,2715.764706,own history,38021.0,Bengaluru,12.9716,77.5946
6,PLANT04,0.428503,554,True,1,3202.747151,network fallback,1774322.0,Indore,22.7196,75.8577
7,PLANT01,0.566976,1070,False,0,3202.747151,network fallback,3426939.0,Kolkata,22.5726,88.3639
8,PLANT07,0.371424,265,False,0,3202.747151,network fallback,848728.0,Chennai,13.0827,80.2707
9,PLANT14,0.634330,549,False,0,3202.747151,network fallback,1758308.0,Ahmedabad,23.0225,72.5714

In [45]:
warehouse_master.to_csv(f"{base}/Data/Processed/warehouse_master.csv", index=False)
customer_demand.to_csv(f"{base}/Data/Processed/customer_demand.csv", index=False)

In [46]:
import numpy as np

# Re-seed so this step is reproducible independently
np.random.seed(42)

customer_cities = {
    'Mumbai': (19.0760,72.8777),
    'Delhi NCR': (28.7041,77.1025),
    'Bengaluru': (12.9716,77.5946),
    'Chennai': (13.0827,80.2707),
    'Kolkata': (22.5726,88.3639),
    'Pune': (18.5204,73.8567),
    'Ahmedabad': (23.0225,72.5714),
    'Hyderabad': (17.3850,78.4867),
    'Jaipur': (26.9124,75.7873),
    'Lucknow': (26.8467,80.9462),
    'Surat': (21.1702,72.8311),
    'Bhopal': (23.2599,77.4126),
    'Patna': (25.5941,85.1376),
    'Kochi': (9.9312,76.2673),
    'Chandigarh': (30.7333,76.7794),
    'Guwahati': (26.1445,91.7362),
    'Coimbatore': (11.0168,76.9558),
    'Visakhapatnam': (17.6868,83.2185),
    'Nagpur': (21.1458,79.0882),
    'Indore': (22.7196,75.8577),
}

cust_names = list(customer_cities.keys())

assigned_cust_cities = np.random.choice(
    cust_names,
    size=len(customer_demand),
    replace=True
)

customer_demand["city"] = assigned_cust_cities

customer_demand["latitude"] = customer_demand["city"].map(
    lambda c: customer_cities[c][0]
)

customer_demand["longitude"] = customer_demand["city"].map(
    lambda c: customer_cities[c][1]
)

# Add a small random offset so customers in the same city don't overlap on the map
customer_demand["latitude"] += np.random.uniform(
    -0.05, 0.05, len(customer_demand)
)

customer_demand["longitude"] += np.random.uniform(
    -0.05, 0.05, len(customer_demand)
)

print(customer_demand["city"].value_counts())
print(f"\nCities used: {customer_demand['city'].nunique()} of 20")

customer_demand.head()

city
Ahmedabad        5
Chandigarh       5
Bhopal           5
Indore           3
Surat            3
Nagpur           3
Hyderabad        3
Delhi NCR        3
Bengaluru        3
Chennai          2
Visakhapatnam    2
Jaipur           2
Pune             1
Mumbai           1
Coimbatore       1
Guwahati         1
Lucknow          1
Kolkata          1
Kochi            1
Name: count, dtype: int64

Cities used: 19 of 20

,Customer,total_units_period,total_weight_period,order_count,avg_daily_demand_units,city,latitude,longitude
0,V55555555_5,8020417,21970.357577,531,1604083.4,Ahmedabad,23.063432,72.568621
1,V55555555555_28,5293676,3451.853820,203,1058735.2,Indore,22.695478,75.819659
2,V55555555_32,1914858,4449.030135,241,382971.6,Chandigarh,30.749552,76.800724
3,V55555_26,1909058,16567.123311,340,381811.6,Surat,21.151371,72.857179
4,V55555_2,1512452,18717.648999,758,302490.4,Hyderabad,17.387007,78.492828

In [47]:
warehouse_master.to_csv(
    f"{base}/Data/Processed/warehouse_master.csv",
    index=False
)

customer_demand.to_csv(
    f"{base}/Data/Processed/customer_demand.csv",
    index=False
)

In [48]:
RENT_PER_SQFT_PER_MONTH_INR = 22
UNITS_PER_SQFT_CAPACITY = 15

annual_rent_per_sqft = RENT_PER_SQFT_PER_MONTH_INR * 12
fixed_cost_per_unit_capacity = annual_rent_per_sqft / UNITS_PER_SQFT_CAPACITY

print(f"Fixed cost per unit capacity/year: ₹{fixed_cost_per_unit_capacity:.2f}")

warehouse_master["annual_fixed_cost"] = (
    warehouse_master["daily_capacity_units"] *
    fixed_cost_per_unit_capacity
).round(0)

warehouse_master[
    [
        "plant_code",
        "is_currently_active",
        "daily_capacity_units",
        "annual_fixed_cost"
    ]
]

Fixed cost per unit capacity/year: ₹17.60

  plant_code  is_currently_active  daily_capacity_units  annual_fixed_cost
0    PLANT16                 True              647548.0         11396845.0
1    PLANT12                 True               78027.0          1373275.0
2    PLANT09                 True               35230.0           620048.0
3    PLANT03                 True             3393463.0         59724949.0
4    PLANT13                 True              247159.0          4349998.0
5    PLANT08                 True               38021.0           669170.0
6    PLANT04                 True             1774322.0         31228067.0
7    PLANT01                False             3426939.0         60314126.0
8    PLANT07                False              848728.0         14937613.0
9    PLANT14                False             1758308.0         30946221.0

In [49]:
warehouse_master.to_csv(
    f"{base}/Data/Processed/warehouse_master.csv",
    index=False
)

In [50]:
ROAD_FREIGHT_RATE_PER_TONNE_KM_INR = 3.78

orders["weight_per_unit"] = orders["Weight"] / orders["Unit quantity"]

volume_weighted_avg = orders["Weight"].sum() / orders["Unit quantity"].sum()
simple_avg = orders["weight_per_unit"].mean()

print(f"Road freight rate: ₹{ROAD_FREIGHT_RATE_PER_TONNE_KM_INR}/tonne-km")
print(f"Simple average: {simple_avg:.6f} kg/unit")
print(f"Volume-weighted average: {volume_weighted_avg:.6f} kg/unit")

AVG_WEIGHT_PER_UNIT_KG = volume_weighted_avg

Road freight rate: ₹3.78/tonne-km
Simple average: 0.015662 kg/unit
Volume-weighted average: 0.006205 kg/unit

In [51]:
ROAD_CIRCUITY_FACTOR = 1.3

def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371
    lat1, lon1, lat2, lon2 = map(np.radians, [lat1, lon1, lat2, lon2])
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = np.sin(dlat / 2) ** 2 + np.cos(lat1) * np.cos(lat2) * np.sin(dlon / 2) ** 2
    return R * 2 * np.arcsin(np.sqrt(a))

dc_cust_pairs = warehouse_master[
    ['plant_code', 'latitude', 'longitude']
].merge(
    customer_demand[
        ['Customer', 'latitude', 'longitude']
    ],
    how='cross',
    suffixes=('_dc', '_cust')
)

dc_cust_pairs['straight_line_km'] = haversine_km(
    dc_cust_pairs['latitude_dc'],
    dc_cust_pairs['longitude_dc'],
    dc_cust_pairs['latitude_cust'],
    dc_cust_pairs['longitude_cust']
)

dc_cust_pairs['road_distance_km'] = (
    dc_cust_pairs['straight_line_km'] * ROAD_CIRCUITY_FACTOR
).round(1)

print(f"Total pairs: {len(dc_cust_pairs)}")

dc_cust_pairs.head()

Total pairs: 460

,plant_code,latitude_dc,longitude_dc,Customer,latitude_cust,longitude_cust,straight_line_km,road_distance_km
0,PLANT16,21.1458,79.0882,V55555555_5,23.063432,72.568621,704.600512,916.0
1,PLANT16,21.1458,79.0882,V55555555555_28,22.695478,75.819659,378.630511,492.2
2,PLANT16,21.1458,79.0882,V55555555_32,30.749552,76.800724,1092.009809,1419.6
3,PLANT16,21.1458,79.0882,V55555_26,21.151371,72.857179,646.151364,840.0
4,PLANT16,21.1458,79.0882,V55555_2,17.387007,78.492828,422.602852,549.4

In [52]:
dc_cust_pairs["freight_cost_per_unit"] = (
    dc_cust_pairs["road_distance_km"]
    * ROAD_FREIGHT_RATE_PER_TONNE_KM_INR
    * (AVG_WEIGHT_PER_UNIT_KG / 1000)
).round(6)

print(
    dc_cust_pairs[
        [
            "plant_code",
            "Customer",
            "road_distance_km",
            "freight_cost_per_unit"
        ]
    ].head()
)

print(f"Minimum freight cost/unit: ₹{dc_cust_pairs['freight_cost_per_unit'].min():.6f}")
print(f"Maximum freight cost/unit: ₹{dc_cust_pairs['freight_cost_per_unit'].max():.6f}")

dc_cust_pairs.to_csv(
    f"{base}/Data/Processed/freight_cost_matrix.csv",
    index=False
)

  plant_code         Customer  road_distance_km  freight_cost_per_unit
0    PLANT16      V55555555_5             916.0               0.021483
1    PLANT16  V55555555555_28             492.2               0.011544
2    PLANT16     V55555555_32            1419.6               0.033294
3    PLANT16        V55555_26             840.0               0.019701
4    PLANT16         V55555_2             549.4               0.012885
Minimum freight cost/unit: ₹0.000021
Maximum freight cost/unit: ₹0.063751

In [53]:
ROAD_FREIGHT_RATE_PER_TONNE_KM_INR = 3.78
MIN_SHIPMENT_CHARGE_INR = 1500

AVG_UNITS_PER_SHIPMENT = orders["Unit quantity"].sum() / len(orders)

min_charge_per_unit = MIN_SHIPMENT_CHARGE_INR / AVG_UNITS_PER_SHIPMENT

dc_cust_pairs["weight_based_cost_per_unit"] = (
    dc_cust_pairs["road_distance_km"]
    * ROAD_FREIGHT_RATE_PER_TONNE_KM_INR
    * AVG_WEIGHT_PER_UNIT_KG
    / 1000
)

dc_cust_pairs["freight_cost_per_unit"] = (
    min_charge_per_unit
    + dc_cust_pairs["weight_based_cost_per_unit"]
).round(4)

print(
    dc_cust_pairs["freight_cost_per_unit"].min(),
    dc_cust_pairs["freight_cost_per_unit"].max()
)

dc_cust_pairs.to_csv(
    f"{base}/Data/Processed/freight_cost_matrix.csv",
    index=False
)

0.4684 0.5321

In [54]:
import pulp

DCs = warehouse_master["plant_code"].tolist()
Customers = customer_demand["Customer"].tolist()

fixed_cost = warehouse_master.set_index("plant_code")["annual_fixed_cost"].to_dict()
variable_cost = warehouse_master.set_index("plant_code")["variable_cost_per_unit"].to_dict()
capacity = warehouse_master.set_index("plant_code")["daily_capacity_units"].to_dict()
demand = customer_demand.set_index("Customer")["avg_daily_demand_units"].to_dict()
freight_cost = dc_cust_pairs.set_index(
    ["plant_code", "Customer"]
)["freight_cost_per_unit"].to_dict()

assert len(fixed_cost) == len(DCs)
assert len(variable_cost) == len(DCs)
assert len(capacity) == len(DCs)
assert len(demand) == len(Customers)
assert len(freight_cost) == len(DCs) * len(Customers)

print("All parameter dictionaries verified complete.")

prob = pulp.LpProblem(
    "Distribution_Network_Optimization",
    pulp.LpMinimize
)

y = pulp.LpVariable.dicts("open", DCs, cat="Binary")
x = pulp.LpVariable.dicts(
    "flow",
    [(i, j) for i in DCs for j in Customers],
    lowBound=0,
    cat="Continuous"
)

print(
    f"Decision variables: {len(y)+len(x)} "
    f"({len(y)} binary + {len(x)} continuous)"
)

All parameter dictionaries verified complete.
Decision variables: 470 (10 binary + 460 continuous)

In [55]:
ANNUAL_OPERATING_DAYS = 250

prob += (
    pulp.lpSum(
        fixed_cost[i] * y[i]
        for i in DCs
    )
    +
    pulp.lpSum(
        (
            variable_cost[i] + freight_cost[(i, j)]
        ) * x[(i, j)] * ANNUAL_OPERATING_DAYS
        for i in DCs
        for j in Customers
    )
), "Total_Annual_Cost"

print("Objective function added successfully.")
print(f"Variables: {len(prob.variables())}")
print(f"Constraints: {len(prob.constraints)}")

Objective function added successfully.
Variables: 470
Constraints: 0

In [56]:
for j in Customers:
    prob += (
        pulp.lpSum(x[(i, j)] for i in DCs) == demand[j],
        f"Demand_{j}"
    )

for i in DCs:
    prob += (
        pulp.lpSum(x[(i, j)] for j in Customers)
        <= capacity[i] * y[i],
        f"Capacity_{i}"
    )

print("Demand and capacity constraints added.")
print(f"Variables: {len(prob.variables())}")
print(f"Constraints: {len(prob.constraints)}")

Demand and capacity constraints added.
Variables: 470
Constraints: 56

In [57]:
solver = pulp.PULP_CBC_CMD(msg=True)

result = prob.solve(solver)

print("Status:", pulp.LpStatus[result])
print(f"Objective value: ₹{pulp.value(prob.objective):,.2f}")

open_dcs = [i for i in DCs if pulp.value(y[i]) > 0.5]

print(f"Open DCs ({len(open_dcs)}):")
print(open_dcs)

Status: Optimal
Objective value: ₹1,507,654,439.57
Open DCs (3):
['PLANT03', 'PLANT04', 'PLANT07']

In [58]:
shipment_plan.to_csv(
    f"{base}/Data/Processed/shipment_plan.csv",
    index=False
)

print("shipment_plan.csv saved successfully.")

NameError: name 'shipment_plan' is not defined

In [ ]:
shipment_plan["annual_units"] = shipment_plan["daily_units"] * ANNUAL_OPERATING_DAYS

dc_summary = (
    shipment_plan
    .groupby("plant_code")
    .agg(
        customers_served=("Customer", "count"),
        daily_units=("daily_units", "sum"),
        annual_units=("annual_units", "sum")
    )
    .reset_index()
)

dc_summary = dc_summary.merge(
    warehouse_master[
        [
            "plant_code",
            "daily_capacity_units",
            "annual_fixed_cost",
            "variable_cost_per_unit",
            "is_currently_active"
        ]
    ],
    on="plant_code"
)

dc_summary["capacity_utilization"] = (
    dc_summary["daily_units"] / dc_summary["daily_capacity_units"] * 100
).round(2)

dc_summary = dc_summary.sort_values(
    "daily_units",
    ascending=False
)

print(dc_summary)

In [ ]:
dc_summary.to_csv(
    f"{base}/Data/Processed/dc_summary.csv",
    index=False
)

print("dc_summary.csv saved.")

In [ ]:
print("Total demand :", customer_demand["avg_daily_demand_units"].sum())
print("Total shipped:", shipment_plan["daily_units"].sum())
print("Difference   :", shipment_plan["daily_units"].sum() -
      customer_demand["avg_daily_demand_units"].sum())

In [ ]:
warehouse_master.to_csv(
    f"{base}/Data/Processed/warehouse_master.csv",
    index=False
)

customer_demand.to_csv(
    f"{base}/Data/Processed/customer_demand.csv",
    index=False
)

dc_cust_pairs.to_csv(
    f"{base}/Data/Processed/freight_cost_matrix.csv",
    index=False
)

shipment_plan.to_csv(
    f"{base}/Data/Processed/shipment_plan.csv",
    index=False
)

dc_summary.to_csv(
    f"{base}/Data/Processed/dc_summary.csv",
    index=False
)

print("All processed files saved successfully.")

In [ ]:
split_customers = (
    shipment_plan.groupby("Customer")["plant_code"]
    .nunique()
    .reset_index(name="dc_count")
)

print(split_customers[split_customers["dc_count"] > 1])

In [ ]:
shipment_plan[
    shipment_plan["Customer"].isin(
        ["V555555555_14", "V55555555_32"]
    )
].sort_values(["Customer", "plant_code"])

In [ ]:
import pandas as pd
import pulp
import os

warehouse_master = pd.read_csv(f"{base}/Data/Processed/warehouse_master.csv")
customer_demand = pd.read_csv(f"{base}/Data/Processed/customer_demand.csv")
freight = pd.read_csv(f"{base}/Data/Processed/freight_cost_matrix.csv")

ANNUAL_OPERATING_DAYS = 250
MIN_SHIPMENT_CHARGE_INR = 1500
AVG_UNITS_PER_SHIPMENT = 3203
min_charge_per_unit = MIN_SHIPMENT_CHARGE_INR / AVG_UNITS_PER_SHIPMENT
SLA_DISTANCE_LIMIT_KM = 600

DCs = warehouse_master["plant_code"].tolist()
Customers = customer_demand["Customer"].tolist()

fixed_cost = warehouse_master.set_index("plant_code")["annual_fixed_cost"].to_dict()
variable_cost = warehouse_master.set_index("plant_code")["variable_cost_per_unit"].to_dict()
capacity = warehouse_master.set_index("plant_code")["daily_capacity_units"].to_dict()
demand = customer_demand.set_index("Customer")["avg_daily_demand_units"].to_dict()
freight_cost = freight.set_index(["plant_code", "Customer"])["freight_cost_per_unit"].to_dict()
distance = freight.set_index(["plant_code", "Customer"])["road_distance_km"].to_dict()

total_demand = sum(demand.values())

def solve_network(sla_multiplier):

    if sla_multiplier is None:
        sla_penalty = {(i, j): 0 for i in DCs for j in Customers}
    else:
        sla_penalty = {
            (i, j): sla_multiplier
            * min_charge_per_unit
            * max(0, distance[(i, j)] - SLA_DISTANCE_LIMIT_KM)
            / 1000
            for i in DCs
            for j in Customers
        }

    prob = pulp.LpProblem("Network", pulp.LpMinimize)

    y = pulp.LpVariable.dicts("open", DCs, cat="Binary")
    x = pulp.LpVariable.dicts(
        "flow",
        [(i, j) for i in DCs for j in Customers],
        lowBound=0,
        cat="Continuous",
    )

    prob += (
        pulp.lpSum(fixed_cost[i] * y[i] for i in DCs)
        + pulp.lpSum(
            (variable_cost[i] + freight_cost[(i, j)] + sla_penalty[(i, j)])
            * x[(i, j)]
            * ANNUAL_OPERATING_DAYS
            for i in DCs
            for j in Customers
        )
    )

    for j in Customers:
        prob += pulp.lpSum(x[(i, j)] for i in DCs) == demand[j]

    for i in DCs:
        prob += (
            pulp.lpSum(x[(i, j)] for j in Customers)
            <= capacity[i] * y[i]
        )

    prob.solve(pulp.PULP_CBC_CMD(msg=0))

    selected = sorted([i for i in DCs if y[i].value() == 1])

    true_cost = (
        sum(
            (variable_cost[i] + freight_cost[(i, j)])
            * x[(i, j)].value()
            * ANNUAL_OPERATING_DAYS
            for i in DCs
            for j in Customers
        )
        + sum(fixed_cost[i] * y[i].value() for i in DCs)
    )

    within_2day = sum(
        x[(i, j)].value()
        for i in DCs
        for j in Customers
        if distance[(i, j)] <= SLA_DISTANCE_LIMIT_KM
    )

    cust_within = sum(
        1
        for j in Customers
        if sum(
            x[(i, j)].value()
            for i in DCs
            if distance[(i, j)] > SLA_DISTANCE_LIMIT_KM
        )
        < 1
    )

    return {
        "sla_multiplier": "baseline" if sla_multiplier is None else sla_multiplier,
        "status": pulp.LpStatus[prob.status],
        "n_dcs_open": len(selected),
        "selected_dcs": ", ".join(selected),
        "true_annual_cost": round(true_cost, 2),
        "cost_vs_baseline_pct": None,
        "sla_volume_pct": round(within_2day / total_demand * 100, 1),
        "sla_customers_pct": round(cust_within / len(Customers) * 100, 1),
    }

sweep_points = [None, 0.5, 1, 3, 5, 8, 12, 15, 18, 20, 25]

results = [solve_network(m) for m in sweep_points]

results_df = pd.DataFrame(results)

baseline_cost = results_df.loc[
    results_df["sla_multiplier"] == "baseline",
    "true_annual_cost",
].iloc[0]

results_df["cost_vs_baseline_pct"] = (
    (results_df["true_annual_cost"] - baseline_cost)
    / baseline_cost
    * 100
).round(2)

print(results_df)

os.makedirs(f"{base}/Outputs/disruption", exist_ok=True)

results_df.to_csv(
    f"{base}/Outputs/disruption/sla_sensitivity_results.csv",
    index=False,
)

print("\nResults saved successfully.")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import os
for root, dirs, files in os.walk("/content/drive/MyDrive"):
    if "freight_cost_matrix.csv" in files:
        print(root)

In [ ]:
base = "/content/drive/MyDrive/Distribution_Network_Optimization"

In [ ]:
import pandas as pd
freight = pd.read_csv(f"{base}/Data/Processed/freight_cost_matrix.csv")
print(freight.columns.tolist())

In [ ]:
base = "/content/drive/MyDrive/Distribution_Network_Optimization"

In [ ]:
print("results_df" in globals())

In [ ]:
import pandas as pd
import pulp
base = "/content/drive/MyDrive/Distribution_Network_Optimization"
warehouse_master = pd.read_csv(f"{base}/Data/Processed/warehouse_master.csv")
customer_demand = pd.read_csv(f"{base}/Data/Processed/customer_demand.csv")
freight = pd.read_csv(f"{base}/Data/Processed/freight_cost_matrix.csv")
ANNUAL_OPERATING_DAYS = 250
MIN_CHARGE_PER_UNIT = 1500 / 3203
DCs = warehouse_master["plant_code"].tolist()
Customers = customer_demand["Customer"].tolist()
fixed_cost = warehouse_master.set_index("plant_code")["annual_fixed_cost"].to_dict()
variable_cost = warehouse_master.set_index("plant_code")["variable_cost_per_unit"].to_dict()
capacity = warehouse_master.set_index("plant_code")["daily_capacity_units"].to_dict()
demand = customer_demand.set_index("Customer")["avg_daily_demand_units"].to_dict()
weight_based = freight.set_index(
    ["plant_code", "Customer"]
)["weight_based_cost_per_unit"].to_dict()
def solve_fuel_scenario(spike):

    freight_cost = {
        (i, j): MIN_CHARGE_PER_UNIT +
        weight_based[(i, j)] * (1 + spike / 100)
        for i in DCs
        for j in Customers
    }

    prob = pulp.LpProblem("FuelScenario", pulp.LpMinimize)

    y = pulp.LpVariable.dicts("open", DCs, cat="Binary")
    x = pulp.LpVariable.dicts(
        "flow",
        [(i, j) for i in DCs for j in Customers],
        lowBound=0
    )

    prob += (
        pulp.lpSum(fixed_cost[i] * y[i] for i in DCs)
        +
        pulp.lpSum(
            (variable_cost[i] + freight_cost[(i, j)])
            * x[(i, j)]
            * ANNUAL_OPERATING_DAYS
            for i in DCs
            for j in Customers
        )
    )

    for j in Customers:
        prob += pulp.lpSum(x[(i, j)] for i in DCs) == demand[j]

    for i in DCs:
        prob += pulp.lpSum(x[(i, j)] for j in Customers) <= capacity[i] * y[i]

    prob.solve(pulp.PULP_CBC_CMD(msg=0))

    selected = sorted(
        [i for i in DCs if y[i].value() == 1]
    )

    cost = pulp.value(prob.objective)

    return selected, cost

baseline_dcs, baseline_cost = solve_fuel_scenario(0)

fuel_results = []

for spike in [0, 4, 10, 25, 60]:

    selected, cost = solve_fuel_scenario(spike)

    fuel_results.append({
        "fuel_spike_pct": spike,
        "selected_dcs": ", ".join(selected),
        "annual_cost": round(cost, 2),
        "cost_change_pct": round(
            (cost - baseline_cost) / baseline_cost * 100,
            3
        ),
        "network_changed": selected != baseline_dcs
    })

fuel_df = pd.DataFrame(fuel_results)

print(fuel_df)

fuel_df.to_csv(
    f"{base}/Data/Processed/fuel_sensitivity_results.csv",
    index=False
)

print("Results saved successfully.")

In [ ]:
import pandas as pd
import pulp

base = "/content/drive/MyDrive/Distribution_Network_Optimization"

warehouse_master = pd.read_csv(f"{base}/Data/Processed/warehouse_master.csv")
customer_demand = pd.read_csv(f"{base}/Data/Processed/customer_demand.csv")
freight = pd.read_csv(f"{base}/Data/Processed/freight_cost_matrix.csv")

In [ ]:
ANNUAL_OPERATING_DAYS = 250

DCs = warehouse_master["plant_code"].tolist()
Customers = customer_demand["Customer"].tolist()

fixed_cost = warehouse_master.set_index("plant_code")["annual_fixed_cost"].to_dict()
variable_cost = warehouse_master.set_index("plant_code")["variable_cost_per_unit"].to_dict()
capacity = warehouse_master.set_index("plant_code")["daily_capacity_units"].to_dict()
demand = customer_demand.set_index("Customer")["avg_daily_demand_units"].to_dict()
freight_cost = freight.set_index(["plant_code","Customer"])["freight_cost_per_unit"].to_dict()

In [ ]:
baseline_cost = 1507654439.57

In [ ]:
def solve_with_failure(failed_dc):

    available_dcs = [dc for dc in DCs if dc != failed_dc]

    prob = pulp.LpProblem("DC_Failure", pulp.LpMinimize)

    y = pulp.LpVariable.dicts("open", available_dcs, cat="Binary")

    x = pulp.LpVariable.dicts(
        "flow",
        [(i, j) for i in available_dcs for j in Customers],
        lowBound=0,
        cat="Continuous"
    )

    prob += (
        pulp.lpSum(fixed_cost[i] * y[i] for i in available_dcs)
        +
        pulp.lpSum(
            (variable_cost[i] + freight_cost[(i, j)])
            * x[(i, j)]
            * ANNUAL_OPERATING_DAYS
            for i in available_dcs
            for j in Customers
        )
    )

    for j in Customers:
        prob += pulp.lpSum(x[(i, j)] for i in available_dcs) == demand[j]

    for i in available_dcs:
        prob += pulp.lpSum(x[(i, j)] for j in Customers) <= capacity[i] * y[i]

    prob.solve(pulp.PULP_CBC_CMD(msg=0))

    selected = sorted(
        [i for i in available_dcs if y[i].value() == 1]
    )

    cost = pulp.value(prob.objective)

    return selected, cost

In [ ]:
failure_results = []

for failed in ["PLANT03", "PLANT04", "PLANT07"]:

    selected, cost = solve_with_failure(failed)

    failure_results.append({
        "failed_dc": failed,
        "replacement_network": ", ".join(selected),
        "annual_cost": round(cost, 2),
        "cost_increase_pct": round(
            (cost - baseline_cost) / baseline_cost * 100,
            2
        )
    })

failure_df = pd.DataFrame(failure_results)

failure_df

In [ ]:
failure_df.to_csv(
    f"{base}/Data/Processed/dc_failure_results.csv",
    index=False
)

print("Results saved successfully.")

In [ ]:
import os
os.makedirs(f"{base}/Outputs", exist_ok=True)
os.makedirs(f"{base}/Outputs/optimized", exist_ok=True)

In [ ]:
print("shipment_plan" in globals())

In [ ]:
import pandas as pd

base = "/content/drive/MyDrive/Distribution_Network_Optimization"

warehouse_master = pd.read_csv(f"{base}/Data/Processed/warehouse_master.csv")
customer_demand = pd.read_csv(f"{base}/Data/Processed/customer_demand.csv")
freight = pd.read_csv(f"{base}/Data/Processed/freight_cost_matrix.csv")

In [ ]:
print("x" in globals(), "y" in globals())

In [ ]:
import pandas as pd
import pulp

base="/content/drive/MyDrive/Distribution_Network_Optimization"

warehouse_master=pd.read_csv(f"{base}/Data/Processed/warehouse_master.csv")
customer_demand=pd.read_csv(f"{base}/Data/Processed/customer_demand.csv")
freight=pd.read_csv(f"{base}/Data/Processed/freight_cost_matrix.csv")

In [ ]:
ANNUAL_OPERATING_DAYS=250

DCs=warehouse_master["plant_code"].tolist()
Customers=customer_demand["Customer"].tolist()

fixed_cost=warehouse_master.set_index("plant_code")["annual_fixed_cost"].to_dict()
variable_cost=warehouse_master.set_index("plant_code")["variable_cost_per_unit"].to_dict()
capacity=warehouse_master.set_index("plant_code")["daily_capacity_units"].to_dict()
demand=customer_demand.set_index("Customer")["avg_daily_demand_units"].to_dict()
freight_cost=freight.set_index(["plant_code","Customer"])["freight_cost_per_unit"].to_dict()

In [ ]:
prob=pulp.LpProblem("Distribution_Network_Optimization",pulp.LpMinimize)

y=pulp.LpVariable.dicts("open",DCs,cat="Binary")
x=pulp.LpVariable.dicts("flow",[(i,j) for i in DCs for j in Customers],lowBound=0)

prob+=(
    pulp.lpSum(fixed_cost[i]*y[i] for i in DCs)+
    pulp.lpSum(
        (variable_cost[i]+freight_cost[(i,j)])
        *x[(i,j)]
        *ANNUAL_OPERATING_DAYS
        for i in DCs
        for j in Customers
    )
)

for j in Customers:
    prob+=pulp.lpSum(x[(i,j)] for i in DCs)==demand[j]

for i in DCs:
    prob+=pulp.lpSum(x[(i,j)] for j in Customers)<=capacity[i]*y[i]

prob.solve(pulp.PULP_CBC_CMD(msg=0))

print(pulp.LpStatus[prob.status])

In [ ]:
rows=[]

for i in DCs:
    for j in Customers:
        if x[(i,j)].value()>0.01:
            rows.append({
                "plant_code":i,
                "Customer":j,
                "daily_units":round(x[(i,j)].value(),1),
                "freight_cost_per_unit":freight_cost[(i,j)],
                "variable_cost_per_unit":variable_cost[i],
                "annual_units":round(x[(i,j)].value()*ANNUAL_OPERATING_DAYS,1)
            })

shipment_plan=pd.DataFrame(rows)

shipment_plan.head()

In [ ]:
print("Rows:",len(shipment_plan))
print("DCs:",shipment_plan["plant_code"].nunique())
print("Customers:",shipment_plan["Customer"].nunique())

print(
    "Split customers:",
    shipment_plan.groupby("Customer").size().gt(1).sum()
)

In [ ]:
import os

os.makedirs(f"{base}/Outputs/optimized", exist_ok=True)

shipment_plan.to_csv(
    f"{base}/Outputs/optimized/shipment_plan.csv",
    index=False
)

print("Shipment plan saved successfully.")

In [ ]:
import os

print(os.listdir(f"{base}/Outputs/optimized"))

In [ ]:
import os

base="/content/drive/MyDrive/Distribution_Network_Optimization"

print("Processed folder:")
print(os.listdir(f"{base}/Data/Processed"))

print("\nOutputs folder:")
if os.path.exists(f"{base}/Outputs"):
    print(os.listdir(f"{base}/Outputs"))
else:
    print("Outputs folder not found")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import os
print(os.listdir("/content/drive/MyDrive"))

In [ ]:
base = "/content/drive/MyDrive/Distribution_Network_Optimization"

print(os.listdir(base))

In [ ]:
import os

print(os.listdir(f"{base}/Data"))
print(os.listdir(f"{base}/Data/Processed"))

In [ ]:
%who

In [ ]:
import pulp
print("PuLP imported successfully")

In [ ]:
%who

In [ ]:
import os
print(os.listdir(f"{base}/Notebooks"))